# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: ICEMortgageTechnology,Inc.Encompass
PackageVersion: 7.0.0.2
PackageLocale: en-US
Publisher: ICE Mortgage Technology, Inc.
PackageName: Encompass
License: Proprietary
Copyright: Copyright (C) 2024 ICE Mortgage Technology, Inc.
ShortDescription: Encompass360 download manages and monitors mortgage documentation.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
