# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ICEMortgageTechnology,Inc.Encompass
PackageVersion: 7.0.0.2
InstallerType: msi
Scope: machine
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Adobe.Acrobat.Reader.64-bit
InstallModes:
- silent
InstallerSwitches:
  Silent: /qn /norestart
UpgradeBehavior: install
ReleaseDate: 2024-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://download.elliemae.com/encompass/install/smartclient/enc360/EncompassDesktop.exe
  InstallerSha256: 29D2556F0B59F81F9378001D005F1EA741B2656A431B334BFD1F4886FDC736DA
  InstallerSwitches: {}
ManifestType: installer
ManifestVersion: 1.9.0
