# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Microsoft.SQLServerManagementStudio
PackageVersion: 20.2.37
PackageLocale: es-ES
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/
PublisherSupportUrl: https://aka.ms/ssms-feedback/
PrivacyUrl: https://privacy.microsoft.com/
Author: Microsoft
PackageName: Microsoft SQL Server Management Studio
PackageUrl: https://learn.microsoft.com/es-ES/sql/ssms/download-sql-server-management-studio-ssms
License: Proprietary
LicenseUrl: https://learn.microsoft.com/es-ES/Legal/sql/sql-server-management-studio-license-terms
Copyright: Copyright (c) Microsoft Corporation
ShortDescription: SQL Server Management Studio (SSMS) es un entorno integrado para administrar cualquier infraestructura de SQL, desde SQL Server a Azure SQL Database
Description: SQL Server Management Studio (SSMS) es un entorno integrado para administrar cualquier infraestructura de SQL, desde SQL Server a Azure SQL Database. SSMS proporciona herramientas para configurar, supervisar y administrar instancias de SQL Server y bases de datos. Use SSMS para implementar, supervisar y actualizar los componentes de nivel de datos que usan las aplicaciones, además de compilar consultas y scripts.
ManifestType: locale
ManifestVersion: 1.9.0
