# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Microsoft.SQLServerManagementStudio
PackageVersion: 20.2.37
PackageLocale: ja-JP
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/
PublisherSupportUrl: https://aka.ms/ssms-feedback/
PrivacyUrl: https://privacy.microsoft.com/
Author: Microsoft
PackageName: Microsoft SQL Server Management Studio
PackageUrl: https://learn.microsoft.com/ja-JP/sql/ssms/download-sql-server-management-studio-ssms
License: Proprietary
LicenseUrl: https://learn.microsoft.com/ja-JP/Legal/sql/sql-server-management-studio-license-terms
Copyright: Copyright (c) Microsoft Corporation
ShortDescription: SQL Server Management Studio (SSMS) は、SQL Server から Azure SQL Database まで、SQL インフラストラクチャを管理するための統合環境です
Description: SQL Server Management Studio (SSMS) は、SQL Server から Azure SQL Database まで、SQL インフラストラクチャを管理するための統合環境です。 SSMS には、SQL Server とデータベースのインスタンスを構成、監視、および管理するためのツールが備わっています。 SSMS を使用して、ご利用のアプリケーションで使われるデータ層コンポーネントを配置、監視、アップグレードしたり、クエリとスクリプトを作成したりすることができます。
ManifestType: locale
ManifestVersion: 1.9.0
