# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PrintNode.PrintNode
PackageVersion: 4.28.13
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{33B13CE8-DE51-4E77-9B65-ED90634A58BF}_is1'
ReleaseDate: 2025-03-11
AppsAndFeaturesEntries:
- ProductCode: '{33B13CE8-DE51-4E77-9B65-ED90634A58BF}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PrintNode'
Installers:
- Architecture: x86
  InstallerUrl: https://dl.printnode.com/client/printnode/4.28.13/PrintNode-4.28.13.exe
  InstallerSha256: D4F01CF06EAD48761A13E932B03976FAE6F4536FFA8EB5ACF1770B3429EA07E7
ManifestType: installer
ManifestVersion: 1.9.0

