# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.16.1
PackageLocale: en-US
Publisher: Nextcloud GmbH
PublisherUrl: https://nextcloud.com/
PublisherSupportUrl: https://github.com/nextcloud/desktop/issues
PrivacyUrl: https://nextcloud.com/privacy
Author: Nextcloud GmbH
PackageName: Nextcloud
PackageUrl: https://nextcloud.com/
License: GPL-2.0
LicenseUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
ShortDescription: The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud Server with your computer.
Description: |-
  Use the desktop clients to keep your files synchronized between your Nextcloud server and your desktop.
  Select one or more directories on your local machine and always have access to your latest files wherever you are.
Moniker: nextclouddesktop
Tags:
- cloud
- cloud-sync
- nextcloud-desktop-client
- synchronization
- utility
ReleaseNotes: |-
  What's Changed
  - [stable-3.16] remove unused capture of this in one lambda by @backportbot in nextcloud/desktop#7985
  - [stable-3.16] fix setups that use basic auth by @backportbot in nextcloud/desktop#7993
  - [stable-3.16] use our own Craft cache for macOS builds by @backportbot in nextcloud/desktop#8003
  - [stable-3.16] Bugfix/do not warn about invalid files in not synced folders by @backportbot in nextcloud/desktop#8001
  - [stable-3.16] Fix version detection by the Ubuntu/Debian build script by @backportbot in nextcloud/desktop#8008
  - [stable-3.16] gui/wizard: Integrate macOS VFS (File Provider) configuration into account wizard by @claucambra in nextcloud/desktop#8006
  - [stable-3.16] gui/tray: Hide resume all menu item when no local sync folders are configured by @backportbot in nextcloud/desktop#8011
  - [stable-3.16] display reshares in sharing dialog by @backportbot in nextcloud/desktop#8013
  - [stable-3.16] Add option to disable virtual files syncing on Windows. by @backportbot in nextcloud/desktop#8002
  - [stable-3.16] Fix build when BUILD_WEBENGINE=OFF by @backportbot in nextcloud/desktop#8015
  - [stable-3.16] gui/macOS: Do not log account detail-related messages that were not sent on dead file provider socket by @backportbot in nextcloud/desktop#8014
  - [stable-3.16] ensure user receiving an encrypted share maintain proper state by @backportbot in nextcloud/desktop#8017
  Full Changelog: nextcloud/desktop@v3.16.0...v3.16.1
ReleaseNotesUrl: https://github.com/nextcloud-releases/desktop/releases/tag/v3.16.1
Documentations:
- DocumentLabel: Nextcloud Desktop Client Manual
  DocumentUrl: https://docs.nextcloud.com/desktop/3.14/
ManifestType: defaultLocale
ManifestVersion: 1.9.0

