# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.16.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: Reboot=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: install
ProductCode: '{996C1ECB-1E29-488E-8DC9-E7AC8D017F1F}'
ReleaseDate: 2025-03-13
AppsAndFeaturesEntries:
- DisplayVersion: 3.16.1.20250313
  ProductCode: '{996C1ECB-1E29-488E-8DC9-E7AC8D017F1F}'
  UpgradeCode: '{FD2FCCA9-BB8F-4485-8F70-A0621B84A7F4}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Nextcloud'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nextcloud-releases/desktop/releases/download/v3.16.1/Nextcloud-3.16.1-x64.msi
  InstallerSha256: E23E9EB5505B75151D426B920A50619E3E237DF2C1C043F8E55AE93D7A4199F2
ManifestType: installer
ManifestVersion: 1.9.0

