# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PremiumSoft.NavicatPremium
PackageVersion: 17.2.7
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- sql
ProductCode: Navicat Premium 17_is1
ReleaseDate: 2025-06-03
AppsAndFeaturesEntries:
- ProductCode: Navicat Premium 17_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PremiumSoft\Navicat Premium 17'
Installers:
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_en_x64.exe
  InstallerSha256: 8A9A3B240569F46139CDAA526A0E7C7B0CA09305D139A38E464A4EBBFA4B1C88
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_en_x64.exe
  InstallerSha256: 8A9A3B240569F46139CDAA526A0E7C7B0CA09305D139A38E464A4EBBFA4B1C88
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.9.0
