# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Figma.Figma
PackageVersion: 125.4.7
UpgradeBehavior: install
Protocols:
- figma
FileExtensions:
- fig
ReleaseDate: 2025-04-29
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.figma.com/win/build/Figma-125.4.7.exe
  InstallerSha256: A0A2292B53CCCA39CCA4A6C60FEBA6E2E395268EFE4E46E457A3A270376CE737
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: Figma
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://desktop.figma.com/win/build/Figma-125.4.7.msi
  InstallerSha256: E20E17594A90D68886F1688A57B7FD992B1D1DE9B94B566243E977DC1374A874
  InstallerSwitches:
    InstallLocation: APPLICATIONROOTDIRECTORY="<INSTALLPATH>"
  ProductCode: '{8AEA5A17-C74C-423B-ADBF-CDD17E0341CF}'
  AppsAndFeaturesEntries:
  - DisplayName: Figma (Machine - MSI)
    Publisher: Figma Inc.
    ProductCode: '{8AEA5A17-C74C-423B-ADBF-CDD17E0341CF}'
    UpgradeCode: '{77F7184C-7DFB-4F84-A34A-A9506F5F1A50}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Figma\app-125.4.7'
ManifestType: installer
ManifestVersion: 1.9.0
