# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Devolutions.Launcher
PackageVersion: 2025.1.37.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ard
- ftp
- http
- https
- rdp
- sftp
- ssh
- telnet
- vnc
- webdav
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: '{6F310D30-1F2C-4267-94B5-9C09F1058F85}'
ReleaseDate: 2025-05-07
AppsAndFeaturesEntries:
- DisplayName: Devolutions Launcher
  ProductCode: '{6F310D30-1F2C-4267-94B5-9C09F1058F85}'
  UpgradeCode: '{CB5FC4EF-9B66-411D-8F6E-2713D2B8F664}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.Devolutions.Launcher.2025.1.37.0.msi
  InstallerSha256: 9CD60286BB88796996CD7DA3747594B635054C60954DF8E115F701ED3630D3A5
ManifestType: installer
ManifestVersion: 1.9.0
