# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: NordSecurity.NordPass
PackageVersion: 6.1.9
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- nordpass
ProductCode: f7c32559-6c31-590a-9972-0bea54b04213
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.npass.app/windows/NordPassSetup.exe
  InstallerSha256: E867F278F5BC13B85B3CC6CE32A0B33C6D61B7DE868C4DBA9020029BA7C612AC
ManifestType: installer
ManifestVersion: 1.9.0
