# Created with komac v2.11.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Proton.ProtonMail
PackageVersion: 1.8.0
PackageLocale: en-US
Publisher: Proton
PackageName: Proton Mail
License: Proprietary
Copyright: Copyright © 2024 Proton
ShortDescription: Proton official desktop application for Proton Mail and Proton Calendar
ManifestType: defaultLocale
ManifestVersion: 1.9.0

