# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PremiumSoft.NavicatPremium
PackageVersion: 17.2.5
InstallerLocale: es
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- sql
ProductCode: Navicat Premium 17_is1
ReleaseDate: 2025-04-29
AppsAndFeaturesEntries:
- ProductCode: Navicat Premium 17_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PremiumSoft\Navicat Premium 17'
Installers:
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_es_x64.exe
  InstallerSha256: 2D39117CE7377DCDB29647633C24C62FB51001B02D5E9C9C4A30A77A445F042D
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_es_x64.exe
  InstallerSha256: 2D39117CE7377DCDB29647633C24C62FB51001B02D5E9C9C4A30A77A445F042D
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.9.0
