# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dialpad.Dialpad
PackageVersion: 2503.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/dialpad_native/stable/win32/x64/DialpadSetup_x64.exe
  InstallerSha256: EAE49CFB620C1AF7AD6F5C8A0338ED6E10FD0B26CE8A3C95FCC71B4F0495AE85
ManifestType: installer
ManifestVersion: 1.9.0
