# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SaeraSoft.CaesiumImageCompressor
PackageVersion: 2.8.3
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
ProductCode: '{C457F5B2-65EB-48E9-9744-A3719FEABA4C}_is1'
ReleaseDate: 2025-03-08
AppsAndFeaturesEntries:
- ProductCode: '{C457F5B2-65EB-48E9-9744-A3719FEABA4C}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Lymphatus/caesium-image-compressor/releases/download/v2.8.3/caesium-image-compressor-2.8.3-win-setup.exe
  InstallerSha256: 2C4F272C2E18D22052C9C784B838251FD553A7B29B619672BAB8C49E3EF730A4
ManifestType: installer
ManifestVersion: 1.9.0

