# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: SaeraSoft.CaesiumImageCompressor
PackageVersion: 2.8.4
PackageLocale: en-US
Publisher: SaeraSoft
PublisherUrl: https://saerasoft.com/caesium
PublisherSupportUrl: https://github.com/Lymphatus/caesium-image-compressor/issues
PrivacyUrl: https://saerasoft.com/privacyPolicy
Author: SaeraSoft
PackageName: Caesium Image Compressor
PackageUrl: https://github.com/Lymphatus/caesium-image-compressor
License: GPL-3.0
LicenseUrl: https://github.com/Lymphatus/caesium-image-compressor/blob/HEAD/LICENSE
Copyright: SaeraSoft & Matteo Paonessa
ShortDescription: Caesium can compress your pictures up to 90% without visible quality loss.
Description: Caesium is an image compression software that helps you store, send and share digital pictures, supporting JPG, PNG and WebP formats. You can quickly reduce the file size (and resolution, if you want) by preserving the overall quality of the image.
Tags:
- caesium
- compression
- image
- jpg
- png
- webp
ReleaseNotes: |-
  Note
  This might be the latest version of the v2 cycle. I'm starting to work to the v3.0.0 version to address a lot of suggestions, feature requests and general improvements. You can participate in the development in this discussion thread.
  Bugfixes
  - Fix #338 - Invalid JPEG quality value on macOS
  - Fix #335 - Internal error 40 for JPEGs
ReleaseNotesUrl: https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.8.4
ManifestType: defaultLocale
ManifestVersion: 1.9.0

