# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 131.0.6778.140
InstallerLocale: en-US
InstallerType: msi
Scope: machine
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- mms
- tel
- webcal
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: '{D9596C6B-431E-3638-ACB7-B4B0D24D2D1B}'
ReleaseDate: 2024-12-10
AppsAndFeaturesEntries:
- DisplayName: Google Chrome
  Publisher: Google LLC
  DisplayVersion: 70.158.32908
  ProductCode: '{D9596C6B-431E-3638-ACB7-B4B0D24D2D1B}'
  UpgradeCode: '{C1DFDF69-5945-32F2-A35E-EE94C99C7CF4}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: 3DF5CD9EFA1E738ABBAA6DDF132ADA759B4266AEAE6C76DCD7907F473108BE80
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 03E04D817154778EFDA80EC6E0FCF1AB9FF6F719848E97E49FC68AAF64152B4B
- Architecture: arm64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise_arm64.msi
  InstallerSha256: A7135B8C49F0BD68272ACB22DAB6600FDA797FA797659C5551D9B84D86E4F9FD
ManifestType: installer
ManifestVersion: 1.9.0
