# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Devolutions.Launcher
PackageVersion: 2025.2.16.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ard
- ftp
- http
- https
- rdp
- sftp
- ssh
- telnet
- vnc
- webdav
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: '{3EFD87C1-11C5-4FFC-9301-2FE4476A1F8E}'
ReleaseDate: 2025-06-19
AppsAndFeaturesEntries:
- DisplayName: Devolutions Launcher
  ProductCode: '{3EFD87C1-11C5-4FFC-9301-2FE4476A1F8E}'
  UpgradeCode: '{CB5FC4EF-9B66-411D-8F6E-2713D2B8F664}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.Devolutions.Launcher.2025.2.16.0.msi
  InstallerSha256: 4ED2F9B402DFBA81DBD3693477F294DFFB2A4E53A348D7D9F71EA6CD9DBBB678
ManifestType: installer
ManifestVersion: 1.10.0
