# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PrintNode.PrintNode
PackageVersion: 4.28.14
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{33B13CE8-DE51-4E77-9B65-ED90634A58BF}_is1'
ReleaseDate: 2025-05-01
AppsAndFeaturesEntries:
- ProductCode: '{33B13CE8-DE51-4E77-9B65-ED90634A58BF}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PrintNode'
Installers:
- Architecture: x86
  InstallerUrl: https://dl.printnode.com/client/printnode/4.28.14/PrintNode-4.28.14.exe
  InstallerSha256: 2A7F0ED460CEE9BD8AC65B51D8DE2C121A0BF3DE72BB19FC5DDB090D8E76A9BC
ManifestType: installer
ManifestVersion: 1.9.0
