# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SiberSystems.RoboForm
PackageVersion: 9.6.8.8
InstallerLocale: en-US
InstallerType: msi
Scope: user
ProductCode: '{D9379E21-D1A6-40E0-8F78-561289BDA28E}'
AppsAndFeaturesEntries:
- ProductCode: '{D9379E21-D1A6-40E0-8F78-561289BDA28E}'
  UpgradeCode: '{1E08EFA2-EE77-499D-8FAE-0C37727FCD51}'
Installers:
- Architecture: x86
  InstallerUrl: https://www.roboform.com/dist/RoboForm-v9-Enterprise.msi
  InstallerSha256: F3B9CDC921BEBB81552F0D93755803EEA74CCEBD134F9E9F9D6D8DC7C9E64AAD
ManifestType: installer
ManifestVersion: 1.9.0
