# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PhraseExpress.PhraseExpress
PackageVersion: 17.0.120
InstallerLocale: en-US
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-04-04
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.exe
  InstallerSha256: 6FE9272E3F599B61D371520CDCFB0B248A364D4FCFD610CF9F02495089734B9C
  InstallerSwitches:
    Custom: /CURRENTUSER
  ProductCode: PhraseExpress_is1
  AppsAndFeaturesEntries:
  - ProductCode: PhraseExpress_is1
  ElevationRequirement: elevatesSelf
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.exe
  InstallerSha256: 6FE9272E3F599B61D371520CDCFB0B248A364D4FCFD610CF9F02495089734B9C
  InstallerSwitches:
    Custom: /ALLUSERS
  ProductCode: PhraseExpress_is1
  AppsAndFeaturesEntries:
  - ProductCode: PhraseExpress_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\PhraseExpress'
- InstallerLocale: de-DE
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.msi
  InstallerSha256: 11EA960A5E0E89EF1976859A3F597B9083F26B1EFB1C5969472F1102513F69BF
  ProductCode: '{3906C279-E875-4D81-950B-983622A0AFB6}'
  AppsAndFeaturesEntries:
  - ProductCode: '{3906C279-E875-4D81-950B-983622A0AFB6}'
    UpgradeCode: '{04F55855-93EA-4A9C-A5CC-A5AA30796893}'
  InstallationMetadata:
    DefaultInstallLocation: APPDIR:.
ManifestType: installer
ManifestVersion: 1.9.0
