# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: DuoSecurity.Duo2FAAuthenticationforWindows
PackageVersion: 4.3.1.4861
PackageLocale: en-US
Publisher: Duo Security Inc.
PackageName: Duo Authentication for Windows Logon
PackageUrl: https://help.duo.com/s/article/3543?language=en_US
License: Copyright (C) 2021 DUO
ShortDescription: Duo integrates with Microsoft Windows client and server operating systems to add two-factor authentication to Remote Desktop and local logons and credentialed UAC elevation prompts.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
