# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Box.BoxTools
PackageVersion: 4.28.1.1163
InstallerLocale: en-US
InstallerType: msi
Scope: machine
ProductCode: '{C7A66B1D-4A7F-4507-B1BA-FD2C2AC025C3}'
ReleaseDate: 2025-03-20
AppsAndFeaturesEntries:
- ProductCode: '{C7A66B1D-4A7F-4507-B1BA-FD2C2AC025C3}'
  UpgradeCode: '{BA743183-92C2-4F8F-B27E-B7822CAD2095}'
InstallationMetadata:
  DefaultInstallLocation: APPDIR:.
Installers:
- Architecture: x86
  InstallerUrl: https://e3.boxcdn.net/box-installers/boxedit/win/currentrelease/BoxToolsInstaller-AdminInstall.msi
  InstallerSha256: 158911AAB0D1C6D5E7D12479803FB805E806F5738C5586610F6FAAE8C6BE3F2D
ManifestType: installer
ManifestVersion: 1.9.0

