# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Box.BoxTools
PackageVersion: 4.28.1.1163
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0

