# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Formlabs.PreForm
PackageVersion: 3.47.1
InstallerType: burn
Scope: machine
ProductCode: '{d987d77e-e2cd-45e8-bc80-c3929cff3f8b}'
ReleaseDate: 2025-04-28
AppsAndFeaturesEntries:
- DisplayVersion: 3.47.1.508
  ProductCode: '{d987d77e-e2cd-45e8-bc80-c3929cff3f8b}'
  UpgradeCode: '{958D43B4-AB83-40EF-936B-B404C3505353}'
  InstallerType: burn
- DisplayName: Bonjour
  DisplayVersion: 3.1.0.1
  ProductCode: '{56DDDFB8-7F79-4480-89D5-25E1F52AB28F}'
  InstallerType: wix
- DisplayVersion: 3.47.1.508
  ProductCode: '{AF88B52D-9D50-4B31-83E3-D107A715DFD6}'
  InstallerType: wix
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Formlabs\PreForm'
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.formlabs.com/PreForm/Release/3.47.1/PreForm_win_3.47.1_release_releaser_508_78748.exe
  InstallerSha256: 65A012FD25170DE7061F7844081D66E66D8C2FAF81526701AEA757B8D6F2770E
ManifestType: installer
ManifestVersion: 1.9.0
