# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Hyperionics.HyperSnap9
PackageVersion: 9.5.2
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: -s -nodeskico
  SilentWithProgress: -s -nodeskico
  InstallLocation: -instdir
UpgradeBehavior: install
ReleaseDate: 2024-09-25
Installers:
- InstallerLocale: de-DE
  Architecture: x86
  InstallerUrl: https://www.hyperionics.com/downloads/HS9Setup.exe
  InstallerSha256: 0D377172EA01D4636CC946D5FF9385E66245DC422837A79ACAE01F31108D0200
- InstallerLocale: de-DE
  Architecture: x86
  InstallerUrl: https://www.hyperionics.com/downloads/HS9Setup.exe
  InstallerSha256: 0D377172EA01D4636CC946D5FF9385E66245DC422837A79ACAE01F31108D0200
- InstallerLocale: en-US
  Architecture: x86
  InstallerUrl: https://www.hyperionics.com/downloads/HS9Setup.exe
  InstallerSha256: 0D377172EA01D4636CC946D5FF9385E66245DC422837A79ACAE01F31108D0200
- InstallerLocale: en-US
  Architecture: x86
  InstallerUrl: https://www.hyperionics.com/downloads/HS9Setup.exe
  InstallerSha256: 0D377172EA01D4636CC946D5FF9385E66245DC422837A79ACAE01F31108D0200
ManifestType: installer
ManifestVersion: 1.9.0
